NEO4J_URI="neo4j+s://827c87b7.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="7jmHcnCaNipJ1ceh_1YBrQwYIao4SLsYb81iHjQ2_jA"
AURA_INSTANCEID="827c87b7"
AURA_INSTANCENAME="Instance01"

OPENAI_API_KEY="sk-proj-2je0eYwOrXW0NDcvsXqCT3BlbkFJA0aihrvR3HBXB3C2PKwL"
OPENAI_MODEL="gpt-3.5-turbo"