NEO4J_URI="YOUR_NEO4J_URI"
NEO4J_USERNAME="YOUR_NEO4J_USERNAME"
NEO4J_PASSWORD="YOUR_PASSWORD"
AURA_INSTANCEID="YOUR_INSTANCE_ID"
AURA_INSTANCENAME="YOUR_INSTANCE_NAME"

OPENAI_API_KEY="YOUR_OPENAI_API_KEY"
OPENAI_MODEL="YOUR_MODEL"